### ISSUE TITLE
Support Hindi Font

### ISSUE THREAD

**Issue by mayankmandloi** [annuSharm/javaGui#1]
use the link 
https://www.google.com/inputtools/windows/
 to download hindi support for windows while downloading check hindi language,

**Comment by mayankmandloi** [comment]
@annuSharm  Any Progress ??

**Comment by annuSharm** [comment]
No??

**Comment by mayankmandloi** [comment]
hindi fonts are working ?

**Comment by annuSharm** [comment]
yes
